/* Generated by provision.py: public verification key only. */
#ifndef FLYSAFE_PUBLIC_KEY_H
#define FLYSAFE_PUBLIC_KEY_H
static const unsigned char flysafe_public_key[32] = {238, 33, 42, 118, 123, 0, 113, 34, 189, 177, 92, 103, 204, 191, 251, 132, 27, 6, 65, 150, 43, 214, 248, 59, 66, 64, 193, 20, 39, 27, 36, 164};
#define FLYSAFE_PUBLIC_KEY_HEX "EE212A767B007122BDB15C67CCBFFB841B0641962BD6F83B4240C114271B24A4"
#endif
